


APP_NAME=agri-assistant
APP_VERSION=1.0.0



POSTGRES_USER=postgres
POSTGRES_PASSWORD=minirag2222
POSTGRES_HOST=pgvector
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE=minirag



FILE_ALLOWED_TYPES=["application/pdf","text/plain"]
FILE_MAX_SIZE=50
FILE_DEFAULT_CHUNK_SIZE=500


GENERATION_BACKEND=OPENAI
OPENAI_API_URL=https://api.groq.com/openai/v1
OPENAI_API_KEY="key___"
GENERATION_MODEL_ID=llama-3.3-70b-versatile
GENERATION_MODEL_ID_LITERAL=["llama-3.3-70b-versatile","llama-3.1-8b-instant"]
GENERATION_DAFAULT_MAX_TOKENS=512
GENERATION_DAFAULT_TEMPERATURE=0.3



EMBEDDING_BACKEND=OPENAI
EMBEDDING_MODEL_ID=nomic-embed-text
EMBEDDING_MODEL_SIZE=768


# INPUT LIMITS

INPUT_DAFAULT_MAX_CHARACTERS=800


VECTOR_DB_BACKEND=PGVECTOR
VECTOR_DB_BACKEND_LITERAL=["QDRANT","PGVECTOR"]
VECTOR_DB_PATH=minirag_vectors
VECTOR_DB_DISTANCE_METHOD=cosine
VECTOR_DB_PGVEC_INDEX_THRESHOLD=100


PRIMARY_LANG=ar
DEFAULT_LANG=ar



AGRO_LIB_BASE_URL=
AGRO_LIB_CRAWL_DELAY=1.0
DEFAULT_KB_PROJECT_ID=1