"""sync_schema

Revision ID: 22bbde28709a
Revises: a1b2c3d4e5f6
Create Date: 2026-06-22 19:36:59.469733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bbde28709a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conv_project_id', table_name='conversation_sessions')
    op.drop_index('ix_conv_session_key', table_name='conversation_sessions')
    op.create_index(op.f('ix_conversation_sessions_session_key'), 'conversation_sessions', ['session_key'], unique=False)
    op.drop_index('ix_knowledge_record_growth_stage', table_name='knowledge_records')
    op.drop_index('ix_knowledge_record_name_topic_region', table_name='knowledge_records')
    op.drop_index('ix_knowledge_record_region', table_name='knowledge_records')
    op.drop_index('ix_knowledge_record_season', table_name='knowledge_records')
    op.drop_index('ix_knowledge_record_variety', table_name='knowledge_records')
    op.drop_column('knowledge_records', 'variety')
    op.drop_column('knowledge_records', 'region')
    op.drop_column('knowledge_records', 'growth_stage')
    op.drop_column('knowledge_records', 'season')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_records', sa.Column('season', sa.VARCHAR(), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=True))
    op.add_column('knowledge_records', sa.Column('growth_stage', sa.VARCHAR(), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=True))
    op.add_column('knowledge_records', sa.Column('region', sa.VARCHAR(), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=True))
    op.add_column('knowledge_records', sa.Column('variety', sa.VARCHAR(), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=True))
    op.create_index('ix_knowledge_record_variety', 'knowledge_records', ['variety'], unique=False)
    op.create_index('ix_knowledge_record_season', 'knowledge_records', ['season'], unique=False)
    op.create_index('ix_knowledge_record_region', 'knowledge_records', ['region'], unique=False)
    op.create_index('ix_knowledge_record_name_topic_region', 'knowledge_records', ['name', 'topic', 'region'], unique=False)
    op.create_index('ix_knowledge_record_growth_stage', 'knowledge_records', ['growth_stage'], unique=False)
    op.drop_index(op.f('ix_conversation_sessions_session_key'), table_name='conversation_sessions')
    op.create_index('ix_conv_session_key', 'conversation_sessions', ['session_key'], unique=False)
    op.create_index('ix_conv_project_id', 'conversation_sessions', ['project_id'], unique=False)
    # ### end Alembic commands ###
