from enum import Enum

class ResponseSignal(Enum):
    FILE_TYPE_NOT_SUPPORTED = "FILE TYPE NOT SUPPORTED"
    FILE_UPLOAD_FAILED = "FILE UPLOAD FAILED"
    FILE_UPLOAD_SUCCESS = "FILE UPLOAD SUCCESS"
    FILE_VALIDATED_SUCCESS = "FILE VALIDATED SUCCESS"
    FILE_SIZE_EXCEEDED = "FILE SIZE EXCEEDED"
    PROCESSING_SUCCESS ="processing _success"
    PROCESSING_FAILED ="processing _failed"